package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"

	"nayan/m/Bigquery"
	Convertor "nayan/m/Convertor"
	synonymgenrator "nayan/m/Synonym_genrator"
	"nayan/m/scripts"
)

// Configuration constants
const (
	// profileKey specifies which configuration profile to use for the translation job
	// This profile contains settings like model name, prompts, and other LLM parameters
	profileKey = "translator_gemini_3_synonyms_gen_zh_to_jp"

	// inputPath is the path to the input CSV file containing the original queries to translate
	inputPath = "original_query_lists/input.csv"

	// outputDir is the directory where the translation results will be saved
	outputDir = "synonyms_genrator_output"

	// csvOutputFileName is the name of the CSV file generated by the translation job
	csvOutputFileName = "translator_gemini_3_synonyms_gen_zh_to_jp.csv"

	// jsonOutputFileName is the name of the JSON file to be created from the CSV output
	jsonOutputFileName = "translator_gemini_3_synonyms_gen_zh_to_jp.json"

	// bigQueryJSONPath is the path to the BigQuery dump JSON file
	bigQueryJSONPath = "bigQueryDump/bigquery.json"

	// bigQueryOutputDir is the directory where BigQuery-enhanced results will be saved
	bigQueryOutputDir = "bigQueryOutput"
)

func main() {
	// Parse command line flags
	setupOnly := flag.Bool("setup", false, "Run setup phase only (translation and conversion, skip BigQuery processing)")
	processBigQueryOnly := flag.Bool("process", false, "Run BigQuery processing only (skip translation)")
	flag.Parse()

	ctx := context.Background()

	// Load configuration profile
	profile, err := synonymgenrator.LoadConfig(profileKey)
	if err != nil {
		log.Fatalf("Failed to load config profile '%s': %v", profileKey, err)
	}

	// Create LLM client.
	llmClient := &synonymgenrator.LLMClient{
		Profile: profile,
	}

	// Check if input file exists
	if _, err := os.Stat(inputPath); os.IsNotExist(err) {
		log.Fatalf("Input file '%s' does not exist", inputPath)
	}

	// Create translator
	translator, err := scripts.NewTranslator(llmClient, profileKey, inputPath, outputDir, true)
	if err != nil {
		log.Fatalf("Failed to create translator: %v", err)
	}

	// Run translation job
	csvPath := outputDir + "/" + csvOutputFileName
	jsonPath := outputDir + "/" + jsonOutputFileName

	// If processBigQueryOnly flag is set, skip translation and conversion
	if !*processBigQueryOnly {
		if err := translator.Run(ctx); err != nil {
			log.Fatalf("Translation job failed: %v", err)
		}

		fmt.Println("Translation job completed successfully!")

		// Convert CSV to JSON format
		fmt.Printf("\nConverting CSV to JSON format...\n")
		fmt.Printf("Input CSV: %s\n", csvPath)
		fmt.Printf("Output JSON: %s\n", jsonPath)

		if err := Convertor.SaveGenratorOutputToJSONFile(csvPath, jsonPath); err != nil {
			log.Fatalf("Failed to convert CSV to JSON: %v", err)
		}

		fmt.Println("CSV to JSON conversion completed successfully!")
	}

	// If setupOnly flag is set, skip BigQuery processing
	if *setupOnly {
		fmt.Println("\n✓ Setup phase completed. Skipping BigQuery processing.")
		return
	}
	if err := Convertor.SaveGenratorOutputToJSONFile(csvPath, jsonPath); err != nil {
		log.Fatalf("Failed to convert CSV to JSON: %v", err)
	}

	fmt.Println("CSV to JSON conversion completed successfully!")

	// Process with BigQuery data
	fmt.Printf("\nProcessing with BigQuery data...\n")
	fmt.Printf("BigQuery JSON: %s\n", bigQueryJSONPath)
	fmt.Printf("Output directory: %s\n", bigQueryOutputDir)

	if err := Bigquery.ProcessCSVWithBigQueryData(csvPath, bigQueryJSONPath, bigQueryOutputDir); err != nil {
		log.Fatalf("Failed to process with BigQuery data: %v", err)
	}

	fmt.Println("BigQuery processing completed successfully!")
	fmt.Printf("Enhanced output saved to: %s/translator_gemini_3_synonyms_gen_zh_to_jp.json\n", bigQueryOutputDir)
}
